### PR TITLE
v1.0.0-canary.2

### PR DESCRIPTION
**Pull request by faultables**

### CODE REVIEW

**Comment by anakmagang** [comment]
Current deployment URL: https://nadya-app-canary-awoubo4ue.now.sh

**Comment by anakmagang** [comment]
Current deployment URL: https://nadya-app-canary-n2hp2i06b.now.sh

**Comment by anakmagang** [comment]
Current deployment URL: https://nadya-app-canary-ocai1sw08.now.sh

**Comment by anakmagang** [comment]
Current deployment URL: https://nadya-app-canary-bk2onua5u.now.sh

**Comment by faultables** [comment]
thank you myself you work so heart

**Pull request merged**
