### PR TITLE
v1.0.0-rc.1

### PR DESCRIPTION
**Pull request by faultables**
WIP

### CODE REVIEW

**Comment by anakmagang** [comment]
Current deployment URL: https://nadya-app-canary-31j7axmad.now.sh

**Comment by faultables** [comment]
Blocked by #41

**Comment by anakmagang** [comment]
Current deployment URL: https://nadya-app-canary-luxotrmt7.now.sh

**Comment by anakmagang** [comment]
Current deployment URL: https://nadya-app-canary-p5w095ebv.now.sh

**Comment by anakmagang** [comment]
Current deployment URL: https://nadya-app-canary-p5w095ebv.now.sh

**Comment by anakmagang** [comment]
Current deployment URL: https://nadya-app-canary-p5w095ebv.now.sh

**Comment by anakmagang** [comment]
Current deployment URL: https://nadya-app-canary-nyspajip7.now.sh

**Pull request merged**
