### PR TITLE
added: dialog component & change shell

### PR DESCRIPTION
**Pull request by r17x**

### CODE REVIEW

**Comment by anakmagang** [comment]
Current deployment URL: https://nadya-app-kx8jjqka9.now.sh

**Comment by r17x** [comment]
@108kb  ini gimana ?

**Comment by faultables** [comment]
sudah di merge

**Comment by faultables** [comment]
Sorry ternyata belum @ri7nz

**Comment by anakmagang** [comment]
Current deployment URL: https://nadya-app-41pjguf10.now.sh

**Comment by faultables** [comment]
Good job pak @ri7nz, thanks

**Pull request merged**
