### PR TITLE
update

### PR DESCRIPTION
**Pull request by faultables**
first of all, I need your attention all @evilfactorylabs/nadya 

Sooo here is some updates.

## Previous workflow

Remember how we do some "contribution" here?

1. fork repo
2. push changes to our `origin`
3. pull request to our `upstream` a.k.a this repo
4. ???
5. profit

In short there is no problem, until here we are. The problem was our build (ehm, deployment) bot won't deploy our app even to our staging environment. Why? Because Travis doesn't "share" the ENVIRONMENT_VARIABLE across repositories (your fork and this repo is different, obviously).

This is "understandable", why? To prevent "malicious code" being executed/deployed. Because it came from the "fork" repo, not the original ones.

There are 2 option here to solve this problem:

1. every member teams should configure the same ENV_VARIABLE which was configured by me.
2. push changes **directly** to our upstream

### Option 1

This is not effective and fun at once. Why? First, we can't predict how often changes with our ENV_VARIABLE, although I was make it to prevent env var changes constantly.  Second, you should have Travis account. Third, you all (@evilfactorylabs/nadya) are maintainers.

### Option 2

So, I should to make a choice. Please please please, update the changes **directly** to our upstream repo, but with format `username/branch-name` like what @ri7nz did. It means, basically, if you want to work some task, something you should do is:

```bash
$ git checkout -b your-username/branch-name
$ git push upstream your-username/branch-name
$ hub pull-request --reviewers some,username --assign username
```

instead of previous ones:

```bash
$ git checkout -b branch-name
$ git push origin branch-name
$ hub pull-request --reviewers some,username --assign username
```

And obviously you can "keep in track" between your fork and this repo by manually doing some pull into local repo.

## how about with "external" contributors?

this is a trade-off from our choices (ehm, me. forcely). First, we cannot "trust" directly to the code changes from external contributor. Are they breaking something? Doing something **evil**? Anything.

Second, ok let's just trust the external contributors. We can give them different environment for our app. Remembering the contribution was just came from us, I will think about this later.

---

That's it!

I will do something fun to keep "your ownership" to this repo, let's just see in my future PR.

This PR will be merged after all @evilfactorylabs/nadya members read this.

Thanks for your attention.

### CODE REVIEW

**Comment by anakmagang** [comment]
Current deployment URL: https://nadya-app-gxlhncilr.now.sh

**Comment by faultables** [comment]
@anakmagang terima kasih sudah kasih URL, tapi elu salah URL bambangggg

**Comment by r17x** [comment]
I take & agree for `option 2`, use branch `username/task` @108kb.

**Review by r17x — APPROVED** [review]

**Review by kevanantha — APPROVED** [review]

**Review by wahudamon — APPROVED** [review]

**Comment by r17x** [comment]
For an external contributor, I think, We need to make `CONTRIBUTION.md` @108kb

**Comment by anakmagang** [comment]
Current deployment URL: https://nadya-app-canary-7hy4p5s64.now.sh

**Comment by faultables** [comment]
> For an external contributor, I think, We need to make CONTRIBUTION.md @108kb

yeah basically I am using the old way by creating `HACKING.md` not `CONTRIBUTION.md`, will rename it. thanks

**Comment by faultables** [comment]
I merge this okok

**Pull request merged**
